// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-Ca-1nZ_VhkPDwrA0BLNcL6j7IobUBs',
    appId: '1:216337744708:web:16e8085769d7b590890d11',
    messagingSenderId: '216337744708',
    projectId: 'motorcycle-rental-2',
    authDomain: 'motorcycle-rental-2.firebaseapp.com',
    storageBucket: 'motorcycle-rental-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyQsF6L1ZWuG6QMLeuMZEN3EKVrmMNWMk',
    appId: '1:216337744708:android:72e4f887e306c2d5890d11',
    messagingSenderId: '216337744708',
    projectId: 'motorcycle-rental-2',
    storageBucket: 'motorcycle-rental-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFmHR8a3jEAjvRr55K3WM9sWQn2YpZoLA',
    appId: '1:216337744708:ios:4b4777761e9966f5890d11',
    messagingSenderId: '216337744708',
    projectId: 'motorcycle-rental-2',
    storageBucket: 'motorcycle-rental-2.firebasestorage.app',
    androidClientId: '216337744708-m4jb11g7krcflgj2mpff47ac7ibm1ben.apps.googleusercontent.com',
    iosClientId: '216337744708-ppj1cebukj2qbs4e4iqlcemmuthaf0h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.moonMotorcycleRedesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFmHR8a3jEAjvRr55K3WM9sWQn2YpZoLA',
    appId: '1:216337744708:ios:4b4777761e9966f5890d11',
    messagingSenderId: '216337744708',
    projectId: 'motorcycle-rental-2',
    storageBucket: 'motorcycle-rental-2.firebasestorage.app',
    androidClientId: '216337744708-m4jb11g7krcflgj2mpff47ac7ibm1ben.apps.googleusercontent.com',
    iosClientId: '216337744708-ppj1cebukj2qbs4e4iqlcemmuthaf0h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.moonMotorcycleRedesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR-Ca-1nZ_VhkPDwrA0BLNcL6j7IobUBs',
    appId: '1:216337744708:web:7aef2c08ff87326c890d11',
    messagingSenderId: '216337744708',
    projectId: 'motorcycle-rental-2',
    authDomain: 'motorcycle-rental-2.firebaseapp.com',
    storageBucket: 'motorcycle-rental-2.firebasestorage.app',
  );
}
